### ISSUE TITLE
Duel improvements (Queue, Elo, Autobroadcast, etc)

### ISSUE THREAD

**Issue by Fraxo** [popstarfreas/DG-TS#21]
**Is your feature request related to a problem? Please describe.**
The current duel command is incredibly lackluster and is very VERY underutilized.
Additionally, during active hours (1 pm ~ 5 pm MTN Time) there is typically upwards of a dozen players online all in FFA at a single time. This makes practice incredibly difficult, as FFA is incredibly chaotic, but being on any earlier or later than this vastly increases the likelihood of encountering players with significantly higher ping than you, which hurts the ability for players to improve.

**Describe the solution you'd like**
The simple explanation is a waiting line for you to enter when you join PvP. 
When you join PvP, you can type /duel, or /join or something alike in order to but put in a queue to duel other players. While in this queue, all of your functions remain the same, you are able to PvP in FFA, accept duel invitations, and leave the dimension. In the event a player leaves the dimension, the easiest solution is just to cancel the duel, HOWEVER, I think it would be a lovely addition if you could go play zombies, or survival, or utilize the other DG services while you are in a ranked queue, and should a duel be accepted, you will be given a short 5-second warning, and will be automatically moved to the PvP dimension. I do not know how possible it is, but this system allows much more player freedom, so I think it is preferable over just canceling the system. If this is a technical difficulty, it should be abandoned, as there are vastly more important things to funnel time and energy into than a small detail like this. 

Ideally, there would be 3 factors that dictate when you're put into a duel with another player.
1. Whether or not you just dueled them, 
2. Their Elo/Points/Rating, 
3. Ping.
In an ideal world, if you duel someone, the system will not put you up against that person again unless there is nobody else in the queue within 10 ~ 30 seconds, to prevent players from boosting each other up in elo drastically. Players of similar elo would be more likely to get matched together, and if someone has significantly higher ping, they should be less likely to get into a match with someone with lower ping, although neither ping nor elo should be a deciding factor, as this would likely entirely kill enjoyment.

**Describe alternatives you've considered**
The middle ground is to abandon the elo/points/rating system, and just give us the duel queue. I feel that this alone would help increase the number of players dueling, as you don't have to go out of your way to request individual players to duel or advertise that you're looking to duel other players, but the inclusion of the elo/point system is a good way to incentivize player activity and player growth and also doubles as a way to help refine the duel queue in the event that PvP activity continues to grow.

**Additional context**
Here are some other small things that would be nice. Many of these Avery and I can do on our own, albeit it's a bit finicky, and there doesn't seem to be anywhere noteworthy with commands written down.
Keeping the current ability to duel players manually would be nice. If an elo system is present, I believe you shouldn't be able to duel players of your choice, as this would allow boosting other players up or down in the rankings manually, but practice duels, and other things alike should not be forcefully removed.
When a duel is over, the results of the duel should be broadcasted to the PvP Dimension (and ONLY the PvP Dimension). Something small to indicate the duel is done, and show the score for others to see. This is another way to incentivize players to duel, but also helps players gauge who's doing well and who isn't. Something simple like "The duel between Rofle (5 - 3) Blanc has ended!"
Auto broadcasting when you join PvP who is in the duel queue, and how to join the duel queue.
Bright red sign at spawn showing commands for dueling.
And finally, please somewhere write down the commands for editing arenas because Avery and I can never remember :(

**Comment by popstarfreas** [comment]
# Proposal
I think going forward that the best management for this is to use what we have for zombies, and that is a lobby management system. The upside of this change is that the same arenas can be in-use by multiple parties and improvements made for Zombies like streamlining how arenas work etc can be applied here too.

## Caveats
The trouble is that right now this is centered around the GameModes lobby, and the preference is that while waiting in the queue for a duel or possibly for any PvP related gamemode (we have some coming) is to treat PvP as it is right now but as the "waiting" lobby. This is still possible but this is an extra piece of functionality because the management system needs to be able communicate with the PvP dimension to pull players out of it.

## But...
Now you did also mention playing anywhere, I think it's not much of a stretch to extend this so it can pull players from any dimension for this purpose, in-fact this might help alleviate the issue of waiting around for pvp-only modes.

## Now on player skill rating
I'd think that a rating system for player skill would be useful for both a non-ranked and ranked based system, both having a separate rating and only ranked having an advertised rating. Using this purely as is might get people stuck in an endless loop of dueling the same person, but I think that it can be useful to shield new players from facing the best people too often. I think ranked should probably have a ping requirement on it as well if we take it seriously.

I'd guess that ranked would be secondary as well, it might even have more restrictions on it, like I said about ping, or ways to pick bans on a couple of weapons per match to try to keep people engaged in variety, But this would all just be built on top of non-ranked.

## So as a whole
I think incremental additions here will work best. Once the next pvp update drops and works we can start going through the steps required to achieve this goal, the smaller the steps, the more often the updates.

Breaking it down:
**Step 1**. Our choice is either to A: use the pvp world as it is right now for the arena "canvas" like I did with zombies or B: start a new one and add the arenas again. This is your choice.
**Step 2**. Add the duel mode to GameModes. This is the simplest form of this idea, which is just reuse everything from zombies, if a player types /join duel, it either puts them in a lobby waiting for 1 other person or it joins an existing one. Once both players are there they get thrown into a duel arena and then shoved back into gamemodes.
**Step 3**. When joining a duel lobby, they are sent to PvP and then sent to the duel match once it's ready
**Step 4**. Players can now type ``/join duel`` in PvP itself and it will work as above
**Step 5**. Outputs of duels are printed in PvP.
**Step 6**. Change duel lobbies so that there's a queue system first, and players are ranked by a basic ELO system. The idea is that the longer they wait, they less the matchmaker will care about putting them with someone close to their skill level.
**Step 7**. The queue system is updated so that it will try not to match the same people together too often.

There's some stuff left out, but I think that paves a path forward.

**Comment by Fraxo** [comment]
> ## But...
> Now you did also mention playing anywhere, I think it's not much of a stretch to extend this so it can pull players from any dimension for this purpose, in-fact this might help alleviate the issue of waiting around for PvP-only modes.

Regarding this, I believe this to be a bonus feature, a QoL improvement, and thus not necessary at all. As long as you're correct in that it's not too much of a stretch to extend, this will be nice, but if it proves troublesome do keep in mind it is by no means necessary, and thus can be glossed over and returned to on a later date.


> or ways to pick bans on a couple of weapons per match to try to keep people engaged in variety

While an interesting idea, I have my doubts that this would be intuitive, and even more so that it would be enjoyable due to the way Terraria's PvP functions. There's almost 2 or 3 weapons that most if not all players will use, and one of those that most players will be exceptionally capable with if they're experienced. Removing that from play gimps those players, which isn't enjoyable when there often isn't a replacement that the player is familiar with.
I think for minigames this is a good idea, but it depends on how intuitive we can make the banning process. For the purposes of dueling, I think it best to put this idea on hold until it comes up as something for other minigames.

> Step 1. Our choice is either to A: use the pvp world as it is right now for the arena "canvas" like I did with zombies or B: start a new one and add the arenas again. This is your choice.

I'm presuming option B just means a new world that we copy-paste our current arenas in, which seems fine but I'm not sure what we gain from doing this as opposed to just using our current world?? I can make a lobby for spawn with warps and stuff, I'm not worried about that, but I can do that with our current world, Avery and or I just need the commands for setting arenas for dueling and stuff like that (as I mentioned before somewhere, we keep forgetting them)
If option B is to entirely start from a fresh world, I still do not see the gain in doing this, as that only stands to drastically increase the workload via making new arenas? I'm only asking for clarification on this, even if just over a message on discord.

**Comment by popstarfreas** [comment]
Ok, like you said, some of the things I said might not work, I don't pvp much myself. However, hopefully this opens up options as we progress to try out such things.

I suppose we are between Stage 1 and Stage 2. The plan for right now is that I will be update the gamemodes server in prep for the duel addition. Then you have to go on via a custom lobby and add the arenas into the system from the world file you gave me.

I'll then hold off and make sure the other change (pvpcontroller update) is finished before continuing with this.

**Comment by popstarfreas** [comment]
Got an update that should support this. Will be testing it out before officially marking that part as done.

**Comment by popstarfreas** [comment]
My target to complete stage 2 is by the end of this week.

**Comment by popstarfreas** [comment]
Duel Tracking is now at https://app.clickup.com/2606080/v/l/6-27800908-1?pr=4633115. Closing this but this will still be used as reference.
