### ISSUE TITLE
More Abilities In Zombies

### ISSUE THREAD

**Issue by DavidCo113** [popstarfreas/DG-TS#44]
## Ability Reminder Message
There should be a message that appears when a round starts that says something like: ("don't forget to select an ability!"[insert list of abilities here])

## Ability Suggestions
The abilities I think should be added are below this section. Each ability should only be activated on round 10 and should require 10000 points to upgrade. They should be upgraded via ``/upgrade`` and players should be reminded, on round 10, i.e. "say /upgrade to upgrade ability to ", [insert upgraded ability name here], " buy for 10000 points, lasts for only this round").

#### S S
Summons the nurse who instead of money uses points and has an inventory button that opens her inventory to give her things bought from the nurse's boyfriend. Requires points to summon, can revive the player for points by double pressing s.

#### W W
Summons the nurse's boyfriend who is a merchant who sells armor and weapons that only the nurse can use in trade for points, can be summoned free of cost, upgrade of self repair.

### Soul Stealer
Soul stealer (when pressing s twice deals 100 damage to the nearest player with the most health/defense and scatters 20 ectoplasm around the map that increase max health by 10 when picked up, upgrade of shaman)

### Turret
Turret (summons ballistas, tier 1-3 = tier 1 ballista, tier 4-5 = tier 2 ballista, tier 6+ tier 3 ballista, does insane damage, needs to recharge overtime, has the same type options sentries have, upgrade of sentry)

### Atomic Bomb
Tiny atomic bomb (acts like a grenade, looks like a red grenade, does 1000 damage, takes 2 minutes to recharge, upgrade of barrage)

### Point Warp
Point warp (does the same thing as time warp but pressing p twice makes coins fall out of the sky, copper = 10, silver = 100, gold = 1000, platinum = 10000, takes 2 minutes to recharge coin rain, upgrade of time warp)

**Comment by popstarfreas** [comment]
Avoid proper case (Each Word Starts With A Capital) please. Try to format your suggestion better too, so it is more readable. I fixed the capitalisation and formatted it somewhat, but it's still annoying to read. 
 Your suggestion is also composed of multiple different suggestions, each separate suggestion needs to be its own issue, otherwise it cannot be properly tagged or closed. Also ``why lasts for only this round``?

** Health Insurance **
 * I don't know if the inventory thing is even possible.
 * How will the revive work in solo or when they are the last to die?
 * You haven't specified the armor nor the weapons, nor how this would be balanced

** Soul Stealer **
 * And that includes the shaman?

** Turret **
 * Not sure what recharge overtime is
 * Don't know why you specified ballista at all. These are barely customisable compared to Sentry Bots

** Point Warp **
 * The only buttons usable are WASD (movement keys), Space (Jump key), 0-9 (slot keys)
 * I don't see any specifics here at all about the drop rate
 * You say "sky" but not all maps have a clear definition of what that means

**Comment by DavidCo113** [comment]
The nurse's inventory will be like a chest menu.
Inventory photo: [https://www.dropbox.com/s/og3kqc5d3twlveb/nurse%20inventory.png?dl=0](url) 
Shop photo: [https://www.dropbox.com/s/el4nsc4yfxzhfvo/nurse%20shop.png?dl=0](url)
The armor could be shown with teleporting invisible sentries and also attack with them also.

**Comment by KceGio** [comment]
Abilities that activate at Round 10 would very much kill sentry farming and make certain sentries completely obsolete, the way it is now is nicer. 

The Soul Stealer will be quite an abusable ability endgame if the lobby has a tank class due to damage reduction, and if the lobby has multiple tanks with paladin's shield damage reduction will completely minimize the damage.

A tiny tweak to the atomic bomb, it will inflict poison, confusion, ichor(for lowered defense cause by confusion)[due to radioactive poisoning] to any player at a 10 block radius of detonation, the radius will increase as the bomb gets more powerful
