### ISSUE TITLE
[Zombies] Remove Globe from Special Map, Fix Mystery Chest

### ISSUE THREAD

**Issue by Marcus101RR** [popstarfreas/DG-TS#70]
Since this concern has come up, I believe removing the Gravity Globe and fixing the Mystery Chest would be a good idea.

**Comment by popstarfreas** [comment]
I assume this on The Ascension. I think the mystery chest on this map was never intended to be there, it just got re-added once the system that re-places chests on load was added.

With the gravity globe, I believe that the plan is to see what happens if the revival spot is moved to the lowest non colliding point, such that people who die in the air will be revivable by people on the ground.
