### ISSUE TITLE
Remove rarity for colors, DTP

### ISSUE THREAD

**Issue by Arthri** [popstarfreas/DG-TS#83]
**Is your feature request related to a problem? Please describe.**
Colors shouldn't have rarity, all colors should have 1 rarity, whether its 12 or 1

**Comment by popstarfreas** [comment]
What does this achieve?

**Comment by KceGio** [comment]
Colors don't really have a point to have rarity, some ugly colors have high rarity and some good colors have low rarity. All colors should have 1 uniform rarity so that no color is better than the other

**Comment by popstarfreas** [comment]
You could say that about most of the items on system, it's purely subjective. I don't think a uniform rarity improves the system in anyway, in fact I think it makes it worse because there are no valuable colors.

**Comment by KceGio** [comment]
To be honest, the only items that have a use for rarity is probably commands

**Comment by popstarfreas** [comment]
But that's not true. Rarity decides drop rates of these items, which defines their scarcity. Items of higher rarity are less common, thus more valuable.

**Comment by popstarfreas** [comment]
Do you have anything more to add? Economically, we need a rarity system so that there are items that are worth more (because they are less common) and items that are worth little (because they are common). Which colors are better is subjective, but their rarity is not, it's defined by the system, the system thus decides how valuable they are economically. Without a rarity system, everything would be worth the same, the supply of all items would be equal. It would be very easy to get whatever you want, which to mean seems like it would make the system less interesting and ultimately more boring.

Thoughts?

**Comment by KceGio** [comment]
If the rarity system for colors won't be removed, I think it should be revamped, colors that are closer to neon and in general better should be higher in rarity, there are many colors of rarity r3+ that are brown and in general very ugly

**Comment by popstarfreas** [comment]
Maybe you can point out what RGB colors you are talking about that are not the correct rarity.
I'm also not saying it won't be removed, but the alternative you have proposed does not seem to me like it would be a good idea.
