### ISSUE TITLE
How to create server

### ISSUE THREAD

**Issue by NOTAD** [popstarfreas/DG-TS#98]
Can you tell me how to create a server that can play games between windows and mobile?  I hope you can help me, just once.  please

**Comment by popstarfreas** [comment]
You can run a mobile server and then use Terraria 1.3.0.7 on PC to join it.
Someone described it here:
https://www.reddit.com/r/Terraria/comments/cx4y0o/terraria_pcmobile_cross_platform_compatibility/eyile05/

We obviously don't do that method because we are primarily a PC server, so we use something different:
https://github.com/popstarfreas/dimensions-mcl

The first method is definitely more suitable if you are playing with friends and not running a public server.
